# Generated by Django 3.1 on 2020-08-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_description', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='kamus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bugis', models.CharField(max_length=225)),
                ('indonesi', models.CharField(max_length=225)),
            ],
        ),
    ]
