# Generated by Django 3.1 on 2020-08-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_description', '0002_kamus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kamus',
            old_name='indonesi',
            new_name='indonesia',
        ),
    ]
