# Generated by Django 3.0.7 on 2020-08-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_description', '0003_auto_20200824_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Histori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.CharField(max_length=225)),
                ('bugis', models.CharField(max_length=225)),
                ('indonesia', models.CharField(max_length=225)),
            ],
        ),
        migrations.AlterField(
            model_name='images',
            name='images',
            field=models.ImageField(default='images/None/no-img.jpg', upload_to='images/'),
        ),
    ]
