# Generated by Django 3.0.7 on 2020-08-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_description', '0004_auto_20200826_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='histori',
            name='akurasi',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
