# Generated by Django 3.0.7 on 2020-08-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_description', '0005_histori_akurasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_latih',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.CharField(max_length=225)),
                ('deskripsi', models.CharField(max_length=225)),
            ],
        ),
    ]
